<?xml version="1.0! encoding="ISO-8859-1" standalone="yes"?>
<!DOCTYPE listado_de_notas [
	<!ELEMENT listado_de_notas (nota+)>
	<!ELEMENT nota (para*,de, titulo,contenido)>
	<!ELEMENT para (#PCDATA)>
	<!ELEMENT de (#PCDATA)>
	<!ELEMENT titulo (#PCDATA)>
	<!ELEMENT contenido (#PCDATA)>
	<!ATTLIST nota dia CDATA>
	<!ATTLIST nota hora CDATA>
]>
<listado_de_notas>
	<nota>
		<para>Pedro</para>
		<de>Laura</de>
		<titulo>Recordatorio</titulo>
		<contenido>A las 7:00 en la puerta del teatro</contenido>
	</nota>
	<nota dia="23/01/2010" hora="13:15">
		<para>Miguel</para>
		<de>Juan</de>
		<titulo>Informes</titulo>
		<contenido>Tienes los informes en el casillero</contenido>
	</nota>
</listado_de_notas>